#!/usr/bin/env python3
import argparse
import json
import os
import re
import subprocess

def colored_text(txt, keys=[]):
    _tmp_out = ''
    for _i_tmp in keys:
        _tmp_out += '\033['+_i_tmp+'m'
    _tmp_out += txt
    if len(keys) > 0: _tmp_out += '\033[0m'

    return _tmp_out

def KILL(log):
    raise RuntimeError('\n '+colored_text('@@@ FATAL', ['1','91'])+' -- '+log+'\n')

def WARNING(log):
    print('\n '+colored_text('@@@ WARNING', ['1','93'])+' -- '+log+'\n')

def MKDIRP(dirpath, verbose=False, dry_run=False):
    if verbose:
        print('\033[1m'+'>'+'\033[0m'+' os.mkdirs("'+dirpath+'")')
    if dry_run:
        return
    try:
      os.makedirs(dirpath)
    except OSError:
      if not os.path.isdir(dirpath):
        raise
    return

def EXE(cmd, suspend=True, verbose=False, dry_run=False):
    if verbose:
        print('\033[1m'+'>'+'\033[0m'+' '+cmd)
    if dry_run:
        return

    _exitcode = os.system(cmd)
    _exitcode = min(255, _exitcode)

    if _exitcode and suspend:
       WARNING(cmd)
       raise RuntimeError(_exitcode)

    return _exitcode

def get_output(cmd, permissive=False):
    prc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding='utf8')

    out, err = prc.communicate()

    if (not permissive) and prc.returncode:
       KILL('get_output -- shell command failed (execute command to reproduce the error):\n'+' '*14+'> '+cmd)

    return (out, err)

def command_output_lines(cmd, stdout=True, stderr=False, permissive=False):
    _tmp_out_ls = []

    if not (stdout or stderr):
       WARNING('command_output_lines -- options "stdout" and "stderr" both set to FALSE, returning empty list')
       return _tmp_out_ls

    _tmp_out = get_output(cmd, permissive=permissive)

    if stdout: _tmp_out_ls += _tmp_out[0].split('\n')
    if stderr: _tmp_out_ls += _tmp_out[1].split('\n')

    return _tmp_out_ls

def group_consecutive(nums):
    if not nums:
        return []

    sorted_nums = sorted(set(nums))
    groups = []
    start = end = sorted_nums[0]

    for n in sorted_nums[1:]:
        if n == end + 1:
            end = n
        else:
            groups.append([start, end])
            start = end = n

    groups.append([start, end])
    return groups

def expand(groups):
    result = set()
    for g in groups:
        result.update(range(g[0], g[-1] + 1))
    return result

def run_brilcalc(brilcalc_cmd):
    result = subprocess.run(["bash"],
        input = f"""
shopt -s expand_aliases
source /cvmfs/cms-bril.cern.ch/cms-lumi-pog/brilws-docker/brilws-env 
{brilcalc_cmd}
""",
        capture_output = True,
        text = True
    )
    return (result.stdout, result.stderr)

def runIsGood_without_rereco(pd_name, run_number):
    if pd_name == 'L1Scouting':
        return (run_number >= 403655)
    elif pd_name == 'L1ScoutingSelection':
        return (run_number >= 403681)
    else:
        raise RuntimeError(f'Invalid type of L1-Scouting data set: {pd_name}')

def runIsGood_with_rereco(pd_name, run_number):
    # Calo-Layer1 readout disabled in the L1-Scouting system
    if run_number >= 402698 and run_number <= 403164:
        return False

    if pd_name == 'L1Scouting':
        # Runs in which CaloTowers were included in the event content of the L1Scouting PD
        return (run_number >= 401279)
    elif pd_name == 'L1ScoutingSelection':
        # Runs in which firmware fixes for orbit and BX counters of CaloL1 data were deployed online
        return (run_number >= 403259 and run_number < 403462) or (run_number >= 403552 and run_number < 403655) or run_number >= 403681
    else:
        raise RuntimeError(f'Invalid type of L1-Scouting data set: {pd_name}')

def prescaleFactor(pd_name, run_number):
    if pd_name == 'L1ScoutingSelection':
        return 1
    elif pd_name != 'L1Scouting':
        raise RuntimeError(f'Invalid dataset name: {pd_name}')

    if run_number >= 401279 and run_number <= 403753:
        return 15
    elif run_number >= 403754:
        return 7
    else:
        raise RuntimeError(f'Invalid run number: {run_number}')

def recorded_luminosity(input_dict, normtag, json_file_prefix, verbose = False):
    ret = 0

    for psFactor in input_dict:
        jsonLabel = json_file_prefix
        if psFactor > 1:
            jsonLabel += f'_prescale{psFactor:02d}'

        json.dump(input_dict[psFactor], open(f'{jsonLabel}.json', 'w'), sort_keys=True, indent=4)

        # Extract value of recorded luminosity from brilcalc output
        brilcalc_cmd = f'brilcalc lumi -u /fb -c web -b "STABLE BEAMS"'
        brilcalc_cmd += f' --normtag {normtag}' * (normtag is not None)
        brilcalc_cmd += f' -i {jsonLabel}.json 2>&1 | tee {jsonLabel}.log'
        if verbose:
            print(f'  {brilcalc_cmd}')

        stdout, stderr = run_brilcalc(brilcalc_cmd)
        stdout_lines = stdout.split('\n')
        lumi_rec = float(stdout_lines[stdout_lines.index('#Summary: ')+4].replace('|','').split()[5])
        lumi_rec /= psFactor
        if verbose:
            print(f'    ({lumi_rec:.4f} /fb)')
        ret += lumi_rec

    return ret

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description = 'Create JSON files to reprocess L1-Scouting CaloL1 data of 2026',
        formatter_class = argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument('-i', '--dqm-json', type=str, default='/eos/user/c/cmsdqm/www/CAF/certification/Collisions26/Collisions26_MLEnhancedGolden_Latest.json',
        help='Path to json file with lumisections certified as good for physics analysis')

    parser.add_argument('-o', '--output-file-prefix', type=str, default='l1sCaloTowersJson2026',
        help='Prefix for the basename of the output files')

    parser.add_argument('-v', '--verbose', action='store_true', default=False,
        help='Verbose output to stdout')

    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument('-n', '--normtag', dest='normtag', type=str, default='/cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_BRIL.json',
        help = 'Path to normtag file to be used when running brilcalc')

    group.add_argument('--no-normtag', dest='normtag', action='store_const', const=None,
        help = 'Do not use normtag when running brilcalc')

    args = parser.parse_args()

    # CaloTowers are read out in the L1-Scouting system only for 2 timeslices out of 9
    caloTowersFraction = 2 / 9

    outputFilePrefix = args.output_file_prefix

    stdout_delimiter = '-'*150

    print(stdout_delimiter)
    print(f'Certified luminosity sections: {args.dqm_json}')
    print(stdout_delimiter)

    dqm_json = json.load(open(args.dqm_json))

    out_lines = []

    l1s_types = ['L1Scouting', 'L1ScoutingSelection']

    l1sReRecoDict = {}

    for era in ['Run2026B', 'Run2026D']:
        if args.verbose:
            print(era)

        jsonDict = dict()
        for l1s_type in l1s_types:
            jsonDict[l1s_type] = dict()
            json_dict = jsonDict[l1s_type]
            datasetExpr = f'/{l1s_type}/{era}-*/L1SCOUT'

            datasets = command_output_lines(f'dasgoclient -query "dataset={datasetExpr}" status=VALID')
            datasets = sorted(list(set([foo for foo in datasets if foo])))

            if len(datasets) != 1:
                raise RuntimeError(f'Unexpected number of primary data sets: {datasets}')

            if args.verbose:
                print(f'  {datasets[0]}')

            for dataset in datasets:
                das_query = f'dasgoclient -query "file,run,lumi dataset={dataset}"'
                frl_lines = [foo for foo in command_output_lines(das_query) if foo]

                for frl_line in frl_lines:
                    frl_line_split = frl_line.split()
                    if len(frl_line_split) != 3:
                        raise RuntimeError(f'invalid output for DAS query "{das_query}" (number of entries different from 3): {frl_line}')

                    runNumber = frl_line_split[1]
                    try:
                        int(runNumber)
                    except:
                        raise RuntimeError(f'invalid output for DAS query "{das_query}" (run number cannot be converted to an integer): {frl_line}')

                    if runNumber not in json_dict:
                        json_dict[runNumber] = set()

                    lumis_str = frl_line_split[2]
                    if not (lumis_str.startswith('[') and lumis_str.endswith(']')):
                        raise RuntimeError(f'invalid output for DAS query "{das_query}" (invalid format for list of luminosity blocks): {frl_line}')
                    for lumi_str in lumis_str[1:-1].split(','):
                        json_dict[runNumber].add(int(lumi_str))

        if args.verbose:
            print(f'  Finding LSs common to both L1-Scouting PDs...')

        # l1sDict: JSON-type dict containing LSs certified as good by DQM, and present in both L1-Scouting PDs
        l1sDict = {}
        for runNumber in jsonDict['L1Scouting']:
            if runNumber in jsonDict['L1ScoutingSelection'] and runNumber in dqm_json:
                common_lumis = jsonDict['L1Scouting'][runNumber] & jsonDict['L1ScoutingSelection'][runNumber] & expand(dqm_json[runNumber])
                if common_lumis:
                    l1sDict[runNumber] = group_consecutive(common_lumis)

        if args.verbose:
            print(f'  Creating output JSON files, and running brilcalc...')

        # runDict*: dicts with prescale factor as key, for different data-quality criteria.
        #  - (1): LS passes calo-only certification, and is present in both L1S PDs.
        #  - (2): satisfies (1), and is good for physics analysis with L1S CaloTowers without reprocessing the L1SCOUT data tier.
        #  - (3): satisfies (1), and is good for physics analysis with L1S CaloTowers after a reprocessing of the L1SCOUT data tier.
        for l1s_type in l1s_types:
            runDict1, runDict2, runDict3 = dict(), dict(), dict()
            for runNumber in l1sDict:
                runNumber_int = int(runNumber)
                psFactor = prescaleFactor(l1s_type, runNumber_int)

                if psFactor not in runDict1:
                    runDict1[psFactor] = dict()
                runDict1[psFactor][runNumber] = l1sDict[runNumber]

                if runIsGood_without_rereco(l1s_type, runNumber_int):
                    if psFactor not in runDict2:
                        runDict2[psFactor] = dict()
                    runDict2[psFactor][runNumber] = l1sDict[runNumber]

                if runIsGood_with_rereco(l1s_type, runNumber_int):
                    if psFactor not in runDict3:
                        runDict3[psFactor] = dict()
                    runDict3[psFactor][runNumber] = l1sDict[runNumber]

                    if l1s_type not in l1sReRecoDict:
                        l1sReRecoDict[l1s_type] = dict()
                    l1sReRecoDict[l1s_type][runNumber] = l1sDict[runNumber]

            # Total recorded luminosity in inverse femtobarns (/fb)
            lumiRec1 = recorded_luminosity(input_dict = runDict1, verbose = args.verbose, normtag = args.normtag, json_file_prefix = f'{outputFilePrefix}_{l1s_type}_{era}_certCaloOnly')
            lumiRec2 = recorded_luminosity(input_dict = runDict2, verbose = args.verbose, normtag = args.normtag, json_file_prefix = f'{outputFilePrefix}_{l1s_type}_{era}_goodWithoutReReco')
            lumiRec3 = recorded_luminosity(input_dict = runDict3, verbose = args.verbose, normtag = args.normtag, json_file_prefix = f'{outputFilePrefix}_{l1s_type}_{era}_goodWithReReco')

            lumiRec2 *= caloTowersFraction
            lumiRec3 *= caloTowersFraction

            out_lines += [f'{era:<10} {l1s_type:<30} {lumiRec1:10.4f} {lumiRec2:10.4f} {lumiRec3:10.4f}']

    print(stdout_delimiter)
    print('')
    print('Era, L1-Scouting data set, Lumi (a) [/fb], Lumi (b) [/fb], Lumi (c) [/fb] ')
    print('  (a) Passing Calo-only certification, and requiring a given LS to be present in both L1-Scouting PDs')
    print('  (b) Usable for physics analysis with L1-Scouting CaloTowers without reprocessing the L1SCOUT data tier')
    print('  (c) Usable for physics analysis with L1-Scouting CaloTowers after a reprocessing of the L1SCOUT data tier')
    print('')

    for out_line in sorted(out_lines):
        print(out_line)

    print(stdout_delimiter)

    for l1s_type in l1s_types:
        out_json_file = f'{outputFilePrefix}_{l1s_type}_goodWithReReco.json'
        json.dump(l1sReRecoDict[l1s_type], open(f'{out_json_file}', 'w'), sort_keys=True, indent=4)
        print(f'Output JSON file: {out_json_file}')

    print(stdout_delimiter)
